# Numpy

NumPy module works with the numerical data. NumPy library provides objects for multi-dimensional arrays. NumPy consumes less memory as compared to Pandas.

In [1]:
import numpy as np

#Printing version number

print(np.__version__)

1.19.5


In [2]:
#Creating a 1 dimensional array

array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [17]:
#Printing type of array object 

print("Array is of type: ", type(array_1d)) 
  
#Printing array dimensions (axes)

print("No. of dimensions: ", array_1d.ndim) 
  
#Printing shape of array 

print("Shape of array: ", array_1d.shape) 
  
#Printing size (total number of elements) of array 

print("Size of array: ", array_1d.size) 
  
#Printing type of elements in array 

print("Array stores elements of type: ", array_1d.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  1
Shape of array:  (5,)
Size of array:  5
Array stores elements of type:  int64


In [5]:
#Creating a multi dimensional array

array_md = np.array([[3, 1, 4, 2], [6, 8, 5, 7], [12, 9, 11, 10]])
array_md

array([[ 3,  1,  4,  2],
       [ 6,  8,  5,  7],
       [12,  9, 11, 10]])

In [7]:
#Sorting a array

np.sort(array_md)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([5, 6, 7, 8])
a, b

(array([1, 2, 3, 4, 5, 6]), array([5, 6, 7, 8]))

In [34]:
#Adding 2 Array into One Array

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [4]:
#Prints the common value between two arrays

np.intersect1d(a,b)

array([5, 6])

In [37]:
#Removes common values

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [13]:
#Replacing all odd numbers in arr with -1

array_1d[array_1d % 2 == 1] = -1
array_1d

array([-1,  2, -1,  4, -1])

In [6]:
#Converting 1D Array to Multi dimensional Array

arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
#Multi dimensional array into 1 dimensional

arr.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Slicing 2D Array

array_slice = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array_slice[1, 2:3]

array([7])

In [9]:
#np.where return the indices if the given condition is satisfied

array_one = np.array([1, 2, 3, 4, 5])
x = np.where((array_one > 2) & (array_one < 4))
x

(array([2]),)

In [12]:
array_flip = np.arange(10).reshape(5,2)

flip = np.flip(array_flip, 0)
print('Original Array: \n', array_flip)
print('Flipped Array: \n', flip)


Original Array: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Flipped Array: 
 [[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [14]:
#Creating identical matrix

identical = np.eye(4)
print(identical)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [87]:
#Squareroot of array elements

array_sqrt = np.array([[16, 20],[30, 10]])

np.sqrt(array_sqrt)

array([[4.        , 4.47213595],
       [5.47722558, 3.16227766]])

In [13]:
#Transpose of Array

array_trans = np.array([[1, 2],[3, 4]])
print("Original Array: \n", array_trans)
print("Transpose of Array: \n", array_trans.T)

Original Array: 
 [[1 2]
 [3 4]]
Transpose of Array: 
 [[1 3]
 [2 4]]
